import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const roomSales = sqliteTable("room_sales", {
  id: text("id").primaryKey(),
  bookingId: text("booking_id"),
  roomId: text("room_id").notNull(),
  guestName: text("guest_name").notNull(),
  guestPhone: text("guest_phone"),
  origin: text("origin").notNull().default("ops"),
  source: text("source").notNull(),
  otaPaymentMode: text("ota_payment_mode").notNull().default("debt"),
  otaCommissionPercent: integer("ota_commission_percent").notNull().default(0),
  otaCommissionKind: text("ota_commission_kind").notNull().default("percent"),
  otaCommissionValue: integer("ota_commission_value").notNull().default(0),
  invoiceRequested: integer("invoice_requested", { mode: "boolean" }).notNull().default(false),
  status: text("status").notNull(),
  checkIn: text("check_in").notNull(),
  checkOut: text("check_out").notNull(),
  checkedInAt: text("checked_in_at"),
  checkedOutAt: text("checked_out_at"),
  adults: integer("adults").notNull().default(1),
  children: integer("children").notNull().default(0),
  rate: integer("rate").notNull().default(0),
  discountKind: text("discount_kind").notNull().default("none"),
  discountValue: integer("discount_value").notNull().default(0),
  deposit: integer("deposit").notNull().default(0),
  checkinPaid: integer("checkin_paid").notNull().default(0),
  checkinMethod: text("checkin_method").notNull().default(""),
  cashPaid: integer("cash_paid").notNull().default(0),
  transferPaid: integer("transfer_paid").notNull().default(0),
  companyPaid: integer("company_paid").notNull().default(0),
  refundCash: integer("refund_cash").notNull().default(0),
  refundTransfer: integer("refund_transfer").notNull().default(0),
  refundCompany: integer("refund_company").notNull().default(0),
  refundedAt: text("refunded_at"),
  breakfast: integer("breakfast", { mode: "boolean" }).notNull().default(true),
  breakfastAdults: integer("breakfast_adults"),
  breakfastChildren: integer("breakfast_children"),
  cars: integer("cars").notNull().default(0),
  bikes: integer("bikes").notNull().default(0),
  pmsCode: text("pms_code"),
  notes: text("notes"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
});

export const saleExtraTypes = sqliteTable("sale_extra_types", {
  id: text("id").primaryKey(),
  code: text("code").notNull().unique(),
  name: text("name").notNull(),
  unitPrice: integer("unit_price").notNull().default(0),
  unit: text("unit").notNull().default("once"),
  unitLabel: text("unit_label"),
  sortOrder: integer("sort_order").notNull().default(0),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
});

export const saleExtras = sqliteTable("sale_extras", {
  id: text("id").primaryKey(),
  bookingId: text("booking_id").notNull(),
  typeId: text("type_id"),
  kind: text("kind").notNull(),
  name: text("name").notNull(),
  qty: integer("qty").notNull().default(1),
  unitPrice: integer("unit_price").notNull().default(0),
  unit: text("unit").notNull().default("once"),
  createdAt: text("created_at").notNull(),
  createdBy: text("created_by"),
});

export const bookingChangeRequests = sqliteTable("booking_change_requests", {
  id: text("id").primaryKey(),
  bookingId: text("booking_id").notNull(),
  kind: text("kind").notNull(),
  status: text("status").notNull().default("pending"),
  summary: text("summary").notNull(),
  beforeJson: text("before_json").notNull(),
  payloadJson: text("payload_json").notNull(),
  proposedJson: text("proposed_json"),
  requestedBy: text("requested_by").notNull(),
  requestedAt: text("requested_at").notNull(),
  reviewedBy: text("reviewed_by"),
  reviewedAt: text("reviewed_at"),
  reviewNote: text("review_note"),
  appliedAt: text("applied_at"),
});
