import { eq } from "drizzle-orm";
import { addDaysVN, addMinutes } from "@/lib/datetime";
import type { AppDb } from "../index";
import * as t from "../schema";
import { DEMO_ROOM_OPS } from "./data";
import type { DemoCtx } from "./demo-ctx";

export async function seedDemoStays(db: AppDb, ctx: DemoCtx) {
  const { now, today, checkinAt, dutyId } = ctx;
    const rooms = await db.select().from(t.rooms);
    for (const room of rooms) {
      const demo = DEMO_ROOM_OPS[room.number];
      await db
        .update(t.rooms)
        .set({
          opsStatus: demo?.ops ?? "vacant_clean",
          hkStatus: demo?.hk ?? "ins",
          assignedTo: demo?.assignedTo ?? null,
          oooReason: null,
          oooApproved: false,
          updatedAt: now,
        })
        .where(eq(t.rooms.id, room.id));
    }
  
    await db.insert(t.stays).values([
      {
        id: "s-201",
        pmsCode: "EZ-88502",
        origin: "ezcloud",
        source: "booking",
        roomId: "r-105",
        guestName: "Nguyễn Thu Hà",
        guestPhone: "0933333444",
        status: "arriving",
        arrivalDate: today,
        departureDate: addDaysVN(today, 3),
        adults: 2,
        children: 1,
        breakfast: true,
        pmsBookingOk: true,
        pmsCheckinOk: false,
        pmsCheckoutOk: false,
        invoiceOk: false,
        paymentNote: null,
        checkinAt: null,
        registrationDueAt: null,
        registrationDoneAt: null,
        registrationReason: null,
        notes: "Đang check-in · ăn chay, dị ứng hải sản",
        createdAt: now,
        updatedAt: now,
        createdBy: dutyId,
        updatedBy: dutyId,
      },
      {
        id: "s-305",
        pmsCode: "EZ-88421",
        origin: "ezcloud",
        source: "agoda",
        roomId: "r-305",
        guestName: "Trần Minh Khoa",
        guestPhone: "0912345678",
        status: "inhouse",
        arrivalDate: today,
        departureDate: addDaysVN(today, 2),
        adults: 2,
        children: 0,
        breakfast: true,
        pmsBookingOk: true,
        pmsCheckinOk: true,
        pmsCheckoutOk: false,
        invoiceOk: false,
        paymentNote: null,
        checkinAt,
        registrationDueAt: addMinutes(checkinAt, 30),
        registrationDoneAt: null,
        registrationReason: null,
        notes: "Vừa nhận phòng · gửi ô tô hầm B1",
        createdAt: now,
        updatedAt: now,
        createdBy: dutyId,
        updatedBy: dutyId,
      },
      {
        id: "s-202",
        pmsCode: "EZ-88310",
        origin: "ezcloud",
        source: "traveloka",
        roomId: "r-202",
        guestName: "Lê Thị Hạnh",
        guestPhone: "0987654321",
        status: "inhouse",
        arrivalDate: addDaysVN(today, -1),
        departureDate: addDaysVN(today, 1),
        adults: 1,
        children: 1,
        breakfast: true,
        pmsBookingOk: true,
        pmsCheckinOk: true,
        pmsCheckoutOk: false,
        invoiceOk: false,
        paymentNote: null,
        checkinAt: addMinutes(now, -800),
        registrationDueAt: addMinutes(now, -770),
        registrationDoneAt: addMinutes(now, -780),
        registrationReason: null,
        notes: "Khách gọi dọn phòng 14:00",
        createdAt: now,
        updatedAt: now,
        createdBy: dutyId,
        updatedBy: dutyId,
      },
      {
        id: "s-102",
        pmsCode: "EZ-88201",
        origin: "ezcloud",
        source: "ezcloud",
        roomId: "r-102",
        guestName: "Phạm Đức Anh",
        guestPhone: "0908888777",
        status: "departing",
        arrivalDate: addDaysVN(today, -2),
        departureDate: today,
        adults: 2,
        children: 0,
        breakfast: true,
        pmsBookingOk: true,
        pmsCheckinOk: true,
        pmsCheckoutOk: false,
        invoiceOk: false,
        paymentNote: null,
        checkinAt: addMinutes(now, -3000),
        registrationDueAt: addMinutes(now, -2970),
        registrationDoneAt: addMinutes(now, -2980),
        registrationReason: null,
        notes: "Checkout 12:00, còn thiếu hóa đơn",
        createdAt: now,
        updatedAt: now,
        createdBy: dutyId,
        updatedBy: dutyId,
      },
    ]);
  
}
