import { addDaysVN, addMinutes, nid } from "@/lib/datetime";
import type { AppDb } from "../index";
import * as t from "../schema";
import { isLocalOpsSeed } from "./data";
import type { DemoCtx } from "./demo-ctx";

export async function seedDemoSales(db: AppDb, ctx: DemoCtx) {
  const { now, today, dutyId } = ctx;
    if (isLocalOpsSeed()) {
      await db.insert(t.roomSales).values([
        {
          id: "sale-401",
          bookingId: "sale-401",
          roomId: "r-401",
          guestName: "Đặng Minh Tuấn",
          guestPhone: "0901222333",
          origin: "ops",
          source: "walk_in",
          status: "inhouse",
          checkIn: today,
          checkOut: addDaysVN(today, 2),
          adults: 2,
          children: 0,
          cars: 1,
          bikes: 0,
          rate: 1200000,
          discountKind: "none",
          discountValue: 0,
          deposit: 500000,
          cashPaid: 500000,
          transferPaid: 0,
          pmsCode: null,
          notes: "Vãng lai, nhận chiều",
          createdAt: now,
          updatedAt: now,
          createdBy: dutyId,
          updatedBy: dutyId,
        },
        {
          id: "sale-508",
          bookingId: "sale-508",
          roomId: "r-508",
          guestName: "Mai Thanh Hà",
          guestPhone: "0918888999",
          origin: "ops",
          source: "phone",
          status: "reserved",
          checkIn: addDaysVN(today, 1),
          checkOut: addDaysVN(today, 3),
          adults: 2,
          children: 1,
          cars: 1,
          bikes: 0,
          rate: 950000,
          discountKind: "none",
          discountValue: 0,
          deposit: 300000,
          cashPaid: 0,
          transferPaid: 300000,
          pmsCode: null,
          notes: "Gọi giữ chỗ, ETA 15:00",
          createdAt: now,
          updatedAt: now,
          createdBy: dutyId,
          updatedBy: dutyId,
        },
        {
          id: "sale-506",
          bookingId: "sale-506",
          roomId: "r-506",
          guestName: "Công ty An Phú",
          guestPhone: "0283999000",
          origin: "ops",
          source: "company",
          status: "reserved",
          checkIn: today,
          checkOut: addDaysVN(today, 1),
          adults: 2,
          children: 0,
          cars: 0,
          bikes: 2,
          rate: 2500000,
          discountKind: "percent",
          discountValue: 10,
          deposit: 0,
          cashPaid: 0,
          transferPaid: 0,
          pmsCode: null,
          notes: "VIP công ty — cần hoa",
          createdAt: now,
          updatedAt: now,
          createdBy: dutyId,
          updatedBy: dutyId,
        },
        {
          id: "sale-304",
          bookingId: "bk-doan",
          roomId: "r-304",
          guestName: "Đoàn Minh Châu",
          guestPhone: "0903777888",
          origin: "ops",
          source: "company",
          status: "reserved",
          checkIn: today,
          checkOut: addDaysVN(today, 2),
          adults: 4,
          children: 1,
          cars: 1,
          bikes: 2,
          rate: 800000,
          discountKind: "amount",
          discountValue: 200000,
          deposit: 1000000,
          cashPaid: 0,
          transferPaid: 1000000,
          pmsCode: null,
          notes: "Đoàn 2 phòng",
          createdAt: now,
          updatedAt: now,
          createdBy: dutyId,
          updatedBy: dutyId,
        },
        {
          id: "sale-404",
          bookingId: "bk-doan",
          roomId: "r-404",
          guestName: "Đoàn Minh Châu",
          guestPhone: "0903777888",
          origin: "ops",
          source: "company",
          status: "reserved",
          checkIn: today,
          checkOut: addDaysVN(today, 2),
          adults: 4,
          children: 1,
          cars: 1,
          bikes: 2,
          rate: 1200000,
          discountKind: "none",
          discountValue: 0,
          deposit: 1000000,
          cashPaid: 0,
          transferPaid: 1000000,
          pmsCode: null,
          notes: "Đoàn 2 phòng",
          createdAt: now,
          updatedAt: now,
          createdBy: dutyId,
          updatedBy: dutyId,
        },
        {
          id: "sale-103",
          bookingId: "sale-103",
          roomId: "r-103",
          guestName: "Lê Hoàng Nam",
          guestPhone: "0905555666",
          origin: "ops",
          source: "walk_in",
          status: "departed",
          checkIn: addDaysVN(today, -2),
          checkOut: today,
          adults: 2,
          children: 0,
          rate: 900000,
          discountKind: "none",
          discountValue: 0,
          deposit: 1800000,
          cashPaid: 800000,
          transferPaid: 1000000,
          pmsCode: null,
          notes: "Đã trả phòng, thu đủ",
          createdAt: now,
          updatedAt: now,
          createdBy: dutyId,
          updatedBy: dutyId,
        },
      ]);
      const seededSales = await db.select().from(t.roomSales);
      if (seededSales.length) {
        await db.insert(t.auditLogs).values(
          seededSales.map((row) => ({
            id: `audit-${row.id}-create`,
            entity: "room_sale",
            entityId: row.id,
            action: "create",
            actorId: row.createdBy || dutyId,
            beforeJson: null,
            afterJson: JSON.stringify(row),
            createdAt: row.createdAt,
          })),
        );
        await db.insert(t.auditLogs).values({
          id: "audit-sale-401-phone",
          entity: "room_sale",
          entityId: "sale-401",
          action: "update",
          actorId: dutyId,
          beforeJson: JSON.stringify({ guestPhone: "0901111222" }),
          afterJson: JSON.stringify({ guestPhone: "0901222333" }),
          createdAt: addMinutes(now, 18),
        });
      }
    }
  
    await db.insert(t.vehicles).values({
      id: nid(),
      stayId: "s-305",
      vehicleType: "Ô tô",
      plate: "51H-223.18",
      location: "Hầm B1-12",
      keyLocation: "Hộc lễ tân số 3",
      notes: "Khách gửi xe khi check-in",
      createdAt: now,
    });
  
}
