export const SCHEMA_PATCHES = [
  "ALTER TABLE tasks ADD COLUMN kind TEXT NOT NULL DEFAULT 'general'",
  "ALTER TABLE tasks ADD COLUMN stay_id TEXT",
  "CREATE INDEX IF NOT EXISTS tasks_kind ON tasks (kind)",
  "CREATE INDEX IF NOT EXISTS tasks_stay ON tasks (stay_id)",
  `CREATE TABLE IF NOT EXISTS push_subscriptions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  user_agent TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
)`,
  "CREATE INDEX IF NOT EXISTS push_subscriptions_user ON push_subscriptions (user_id)",
  "ALTER TABLE reception_week_slots ADD COLUMN effective_from TEXT NOT NULL DEFAULT '1970-01-01'",
  "DROP INDEX IF EXISTS reception_week_slots_day_shift",
  "CREATE UNIQUE INDEX IF NOT EXISTS reception_week_slots_day_shift_from ON reception_week_slots (weekday, shift_type, effective_from)",
  "ALTER TABLE room_types ADD COLUMN base_rate INTEGER NOT NULL DEFAULT 0",
  `CREATE TABLE IF NOT EXISTS room_sales (
  id TEXT PRIMARY KEY,
  room_id TEXT NOT NULL,
  guest_name TEXT NOT NULL,
  guest_phone TEXT,
  source TEXT NOT NULL,
  status TEXT NOT NULL,
  check_in TEXT NOT NULL,
  check_out TEXT NOT NULL,
  adults INTEGER NOT NULL DEFAULT 1,
  children INTEGER NOT NULL DEFAULT 0,
  rate INTEGER NOT NULL DEFAULT 0,
  discount_kind TEXT NOT NULL DEFAULT 'none',
  discount_value INTEGER NOT NULL DEFAULT 0,
  deposit INTEGER NOT NULL DEFAULT 0,
  pms_code TEXT,
  notes TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  created_by TEXT,
  updated_by TEXT
)`,
  "CREATE INDEX IF NOT EXISTS room_sales_room ON room_sales (room_id)",
  "CREATE INDEX IF NOT EXISTS room_sales_dates ON room_sales (check_in, check_out)",
  "CREATE INDEX IF NOT EXISTS room_sales_status ON room_sales (status)",
  "ALTER TABLE room_types ADD COLUMN weekend_rate INTEGER NOT NULL DEFAULT 0",
  "ALTER TABLE room_sales ADD COLUMN discount_kind TEXT NOT NULL DEFAULT 'none'",
  "ALTER TABLE room_sales ADD COLUMN discount_value INTEGER NOT NULL DEFAULT 0",
  "ALTER TABLE room_sales ADD COLUMN origin TEXT NOT NULL DEFAULT 'ops'",
  "ALTER TABLE stays ADD COLUMN origin TEXT NOT NULL DEFAULT 'ops'",
  "ALTER TABLE stays ADD COLUMN source TEXT NOT NULL DEFAULT 'walk_in'",
  "CREATE INDEX IF NOT EXISTS room_sales_origin ON room_sales (origin)",
  "CREATE INDEX IF NOT EXISTS room_sales_source ON room_sales (source)",
  "CREATE INDEX IF NOT EXISTS stays_origin ON stays (origin)",
  "ALTER TABLE checklists ADD COLUMN kind TEXT NOT NULL DEFAULT 'shift_open'",
  "ALTER TABLE checklists ADD COLUMN stay_id TEXT",
  "ALTER TABLE checklists ADD COLUMN room_id TEXT",
  "ALTER TABLE checklists ADD COLUMN task_id TEXT",
  "ALTER TABLE checklists ADD COLUMN date TEXT",
  "ALTER TABLE checklist_items ADD COLUMN item_key TEXT",
  "ALTER TABLE checklist_items ADD COLUMN note TEXT",
  "ALTER TABLE checklist_items ADD COLUMN photo TEXT",
  "CREATE INDEX IF NOT EXISTS checklists_kind_date ON checklists (kind, date)",
  "CREATE INDEX IF NOT EXISTS checklists_task ON checklists (task_id)",
  "CREATE INDEX IF NOT EXISTS checklists_room ON checklists (room_id)",
  "CREATE INDEX IF NOT EXISTS audit_logs_created ON audit_logs (created_at)",
  "CREATE INDEX IF NOT EXISTS audit_logs_entity ON audit_logs (entity, created_at)",
  "ALTER TABLE room_sales ADD COLUMN booking_id TEXT",
  "CREATE INDEX IF NOT EXISTS room_sales_booking ON room_sales (booking_id)",
  `CREATE TABLE IF NOT EXISTS sale_extra_types (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  unit_price INTEGER NOT NULL DEFAULT 0,
  unit TEXT NOT NULL DEFAULT 'once',
  unit_label TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1
)`,
  `CREATE TABLE IF NOT EXISTS sale_extras (
  id TEXT PRIMARY KEY,
  booking_id TEXT NOT NULL,
  type_id TEXT,
  kind TEXT NOT NULL,
  name TEXT NOT NULL,
  qty INTEGER NOT NULL DEFAULT 1,
  unit_price INTEGER NOT NULL DEFAULT 0,
  unit TEXT NOT NULL DEFAULT 'once',
  created_at TEXT NOT NULL,
  created_by TEXT
)`,
  "CREATE INDEX IF NOT EXISTS sale_extras_booking ON sale_extras (booking_id)",
  "ALTER TABLE room_sales ADD COLUMN breakfast INTEGER NOT NULL DEFAULT 1",
  "ALTER TABLE room_sales ADD COLUMN discount_kind TEXT DEFAULT 'none'",
  "ALTER TABLE room_sales ADD COLUMN discount_value INTEGER DEFAULT 0",
  "ALTER TABLE room_sales ADD COLUMN cash_paid INTEGER NOT NULL DEFAULT 0",
  "ALTER TABLE room_sales ADD COLUMN transfer_paid INTEGER NOT NULL DEFAULT 0",
  "UPDATE room_sales SET transfer_paid = deposit WHERE deposit > 0 AND cash_paid = 0 AND transfer_paid = 0",
  "ALTER TABLE room_types ADD COLUMN adults INTEGER DEFAULT 0",
  "ALTER TABLE room_sales ADD COLUMN cars INTEGER DEFAULT 0",
  "ALTER TABLE room_sales ADD COLUMN bikes INTEGER DEFAULT 0",
  "ALTER TABLE room_sales ADD COLUMN breakfast_adults INTEGER",
  "ALTER TABLE room_sales ADD COLUMN breakfast_children INTEGER",
  "UPDATE room_sales SET breakfast_adults = CASE WHEN breakfast = 0 THEN 0 ELSE adults END WHERE breakfast_adults IS NULL",
  "UPDATE room_sales SET breakfast_children = CASE WHEN breakfast = 0 THEN 0 ELSE children END WHERE breakfast_children IS NULL",
  "ALTER TABLE room_sales ADD COLUMN company_paid INTEGER NOT NULL DEFAULT 0",
  "ALTER TABLE room_sales ADD COLUMN ota_payment_mode TEXT NOT NULL DEFAULT 'debt'",
  "ALTER TABLE room_sales ADD COLUMN invoice_requested INTEGER NOT NULL DEFAULT 0",
  "ALTER TABLE stays ADD COLUMN invoice_requested INTEGER NOT NULL DEFAULT 0",
  "ALTER TABLE users ADD COLUMN email TEXT",
  "CREATE UNIQUE INDEX IF NOT EXISTS users_email ON users (email)",
  "ALTER TABLE users ADD COLUMN session_version INTEGER NOT NULL DEFAULT 0",
  `CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL
)`,
  "CREATE INDEX IF NOT EXISTS password_reset_tokens_user ON password_reset_tokens (user_id)",
  "CREATE INDEX IF NOT EXISTS password_reset_tokens_expires ON password_reset_tokens (expires_at)",
];
