
export const INGEST_ACTOR_ID = "ingest-agent";

export const AUDIT_ENTITIES = [
  "task",
  "stay",
  "room_sale",
  "room",
  "room_type",
  "shift",
  "checklist_item",
  "user",
  "handover",
  "breakfast",
  "form",
  "incident",
  "vehicle",
  "guest_request",
  "roster_week",
  "roster_day",
  "sale_extra",
  "sale_extra_type",
  "booking",
] as const;

export const AUDIT_ACTIONS = [
  "create",
  "update",
  "delete",
  "open",
  "close",
  "status",
  "save",
  "done",
  "undo",
  "skip",
  "checkin",
  "checkout",
  "cancel",
  "no_show",
  "ingest",
  "accept",
  "lock",
  "unlock",
  "reset_password",
  "rename",
  "set_type",
  "rate",
  "clear",
] as const;

export const AUDIT_ENTITY_LABEL: Record<string, string> = {
  task: "Việc",
  stay: "Khách",
  room_sale: "Chỗ bán",
  room: "Phòng",
  room_type: "Hạng phòng",
  shift: "Ca",
  checklist_item: "Checklist",
  user: "Nhân viên",
  handover: "Bàn giao",
  breakfast: "Ăn sáng",
  form: "Biểu mẫu",
  incident: "Sự cố",
  vehicle: "Xe khách",
  guest_request: "Yêu cầu khách",
  roster_week: "Lịch tuần",
  roster_day: "Đổi ca ngày",
  sale_extra: "Dịch vụ booking",
  sale_extra_type: "Giá dịch vụ",
  booking: "Booking",
};

export const AUDIT_ACTION_LABEL: Record<string, string> = {
  create: "Thêm mới",
  update: "Sửa",
  delete: "Xóa",
  open: "Mở",
  close: "Đóng",
  status: "Đổi trạng thái",
  save: "Lưu",
  done: "Đánh dấu xong",
  undo: "Bỏ đánh dấu",
  skip: "Bỏ qua",
  checkin: "Nhận phòng",
  checkout: "Trả phòng",
  cancel: "Hủy",
  no_show: "No-show",
  ingest: "Đồng bộ PMS",
  accept: "Nhận",
  lock: "Khóa",
  unlock: "Mở khóa",
  reset_password: "Đặt lại mật khẩu",
  rename: "Đổi tên",
  set_type: "Đổi hạng",
  rate: "Sửa giá",
  clear: "Xóa lịch",
};

export const FIELD_LABEL: Record<string, string> = {
  content: "Nội dung",
  status: "Trạng thái",
  guestName: "Khách",
  guestPhone: "Điện thoại",
  pmsCode: "Mã PMS",
  roomId: "Phòng",
  bookingId: "Booking",
  fullName: "Họ tên",
  username: "Tài khoản",
  email: "Email",
  role: "Vai trò",
  active: "Hoạt động",
  type: "Loại",
  name: "Tên",
  number: "Số phòng",
  hkStatus: "HK",
  opsStatus: "Ops",
  notes: "Ghi chú",
  note: "Ghi chú",
  reason: "Lý do",
  skipReason: "Bỏ qua",
  closeReason: "Lý do đóng",
  done: "Xong",
  rate: "Giá",
  baseRate: "Giá thường",
  weekendRate: "Giá lễ tết",
  checkIn: "Nhận",
  checkOut: "Trả",
  arrivalDate: "Đến",
  departureDate: "Đi",
  source: "Nguồn",
  origin: "Xuất xứ",
  adults: "NL",
  children: "TE",
  breakfastAdults: "NL ăn sáng",
  breakfastChildren: "TE ăn sáng",
  cars: "Ô tô",
  bikes: "Xe máy",
  discountKind: "Chiết khấu",
  discountValue: "Mức CK",
  deposit: "Cọc",
  cashPaid: "Tiền mặt",
  transferPaid: "CK cá nhân",
  companyPaid: "CK công ty",
  breakfast: "Ăn sáng",
  qty: "Số lượng",
  unitPrice: "Đơn giá",
  unit: "Đơn vị",
  formCode: "Mẫu",
  title: "Tiêu đề",
  label: "Mục",
  assignedTo: "Giao cho",
  priority: "Ưu tiên",
  dueAt: "Hạn",
  kind: "Loại",
  date: "Ngày",
  count: "Số dòng",
  effectiveFrom: "Áp dụng từ",
  reset: "Đặt lại MK",
};

export const SKIP_FIELDS = new Set([
  "passwordHash",
  "photo",
  "id",
  "createdAt",
  "updatedAt",
  "updatedBy",
  "createdBy",
  "openedAt",
  "openedBy",
  "closedAt",
  "closedBy",
  "acceptedAt",
  "zaloMessage",
  "bookingId",
]);
