
export const INGEST_ACTOR_ID = "ingest-agent";

export const AUDIT_ENTITIES = [
  "task",
  "stay",
  "room_sale",
  "room",
  "room_type",
  "shift",
  "checklist_item",
  "user",
  "handover",
  "breakfast",
  "form",
  "incident",
  "vehicle",
  "guest_request",
  "roster_week",
  "roster_day",
  "sale_extra",
  "sale_extra_type",
  "booking",
  "settings",
] as const;

export const AUDIT_ACTIONS = [
  "create",
  "update",
  "delete",
  "open",
  "close",
  "status",
  "save",
  "done",
  "undo",
  "skip",
  "checkin",
  "checkout",
  "cancel",
  "no_show",
  "ingest",
  "accept",
  "lock",
  "unlock",
  "reset_password",
  "change_password",
  "reset_password_email",
  "rename",
  "set_type",
  "rate",
  "clear",
  "request",
  "approve",
  "reject",
  "conflict",
] as const;

export const AUDIT_ENTITY_LABEL: Record<string, string> = {
  task: "Việc",
  stay: "Khách",
  room_sale: "Chỗ bán",
  room: "Phòng",
  room_type: "Hạng phòng",
  shift: "Ca",
  checklist_item: "Checklist",
  user: "Nhân viên",
  handover: "Bàn giao",
  breakfast: "Ăn sáng",
  form: "Biểu mẫu",
  incident: "Sự cố",
  vehicle: "Xe khách",
  guest_request: "Yêu cầu khách",
  roster_week: "Lịch tuần",
  roster_day: "Đổi ca ngày",
  sale_extra: "Dịch vụ booking",
  sale_extra_type: "Giá dịch vụ",
  booking: "Booking",
  settings: "Cấu hình",
};

export const AUDIT_ACTION_LABEL: Record<string, string> = {
  create: "Thêm mới",
  update: "Sửa",
  delete: "Xóa",
  open: "Mở",
  close: "Đóng",
  status: "Đổi trạng thái",
  save: "Lưu",
  done: "Đánh dấu xong",
  undo: "Bỏ đánh dấu",
  skip: "Bỏ qua",
  checkin: "Nhận phòng",
  checkout: "Trả phòng",
  cancel: "Hủy",
  no_show: "No-show",
  ingest: "Đồng bộ PMS",
  accept: "Nhận",
  lock: "Khóa",
  unlock: "Mở khóa",
  reset_password: "Đặt lại mật khẩu",
  change_password: "Đổi mật khẩu",
  reset_password_email: "Đặt lại mật khẩu",
  rename: "Đổi tên",
  set_type: "Đổi hạng",
  rate: "Sửa giá",
  clear: "Xóa lịch",
  request: "Gửi duyệt",
  approve: "Phê duyệt",
  reject: "Từ chối",
  conflict: "Xung đột",
};

export const FIELD_LABEL: Record<string, string> = {
  content: "Nội dung",
  status: "Trạng thái",
  guestName: "Khách",
  guestPhone: "Điện thoại",
  pmsCode: "Mã booking / PMS",
  roomId: "Phòng",
  bookingId: "Booking",
  fullName: "Họ tên",
  username: "Tài khoản",
  email: "Email",
  role: "Vai trò",
  departmentCode: "Bộ phận",
  active: "Hoạt động",
  enabled: "Giới hạn IP lễ tân",
  ip: "IP được phép",
  type: "Loại",
  name: "Tên",
  number: "Số phòng",
  hkStatus: "HK",
  opsStatus: "Ops",
  notes: "Ghi chú",
  note: "Ghi chú",
  reason: "Lý do",
  skipReason: "Bỏ qua",
  closeReason: "Lý do đóng",
  done: "Xong",
  rate: "Giá",
  baseRate: "Giá thường",
  weekendRate: "Giá lễ tết",
  checkIn: "Ngày nhận phòng",
  checkOut: "Ngày trả phòng",
  arrivalDate: "Ngày khách đến",
  departureDate: "Ngày khách đi",
  source: "Kênh đặt phòng",
  origin: "Nguồn dữ liệu",
  otaPaymentMode: "Hình thức thanh toán OTA",
  invoiceRequested: "Yêu cầu xuất hóa đơn",
  adults: "Người lớn lưu trú",
  children: "Trẻ em lưu trú",
  breakfastAdults: "Người lớn ăn sáng",
  breakfastChildren: "Trẻ em ăn sáng",
  cars: "Ô tô",
  bikes: "Xe máy",
  discountKind: "Loại chiết khấu",
  discountValue: "Mức chiết khấu",
  deposit: "Đặt cọc / đã thu",
  checkinPaid: "Thu đủ khi check-in",
  cashPaid: "Đã thu tiền mặt",
  transferPaid: "Đã thu chuyển khoản cá nhân",
  companyPaid: "Đã thu chuyển khoản công ty",
  paymentMethod: "Hình thức thanh toán",
  breakfast: "Bao gồm ăn sáng",
  qty: "Số lượng",
  unitPrice: "Đơn giá",
  unit: "Đơn vị",
  formCode: "Mẫu",
  title: "Tiêu đề",
  label: "Mục",
  assignedTo: "Người phụ trách",
  acceptedBy: "Người nhận bàn giao",
  doneBy: "Người hoàn thành",
  priority: "Ưu tiên",
  dueAt: "Hạn",
  kind: "Loại",
  date: "Ngày",
  count: "Số dòng",
  effectiveFrom: "Áp dụng từ ngày",
  reset: "Đặt lại MK",
  summary: "Nội dung đề nghị",
  reviewNote: "Lý do xử lý",
};

export const SKIP_FIELDS = new Set([
  "passwordHash",
  "photo",
  "id",
  "createdAt",
  "updatedAt",
  "updatedBy",
  "createdBy",
  "requestId",
  "openedAt",
  "openedBy",
  "closedAt",
  "closedBy",
  "acceptedAt",
  "changed",
  "reset",
  "zaloMessage",
  "bookingId",
]);
